version: '3.8'

services:
  flask:
    depends_on:
      - db
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - 5000:5000
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=linkshorter
    ports:
      - 5432:5432

volumes:
  postgres_data: